[TASK] Add EXT:extension_builder to `ddev fetch-manuals`
In addition to the official TYPO3 documentation manuals the command
```
ddev fetch-manuals
```
starts cloning other officially supported TYPO3 projects that contain
a `screenshots.json` file.

To keep cloning restricted to the official TYPO3 documentation manuals,
use
```
ddev fetch-manuals -c documentation
```
instead.

The first project to be cloned is EXT:extension_builder from
Friends of TYPO3.

diff --git a/.ddev/commands/web/fetch-manuals b/.ddev/commands/web/fetch-manuals
--- a/.ddev/commands/web/fetch-manuals
+++ b/.ddev/commands/web/fetch-manuals
@@ -2,14 +2,60 @@
 
 ## Description: Fetch all official TYPO3 Documentation manuals
 ## Usage: fetch-manuals
-## Example: fetch-manuals
+## Example: fetch-manuals\nfetch-manuals -c documentation
+## Flags: [{"Name":"category","Shorthand":"c","Type":"string","Usage":"Clone only manuals of the selected category (documentation, application). Manuals of all categories if empty."}]
 
 TARGET_BASEPATH="/var/www/html/public/t3docs"
+CATEGORY=""
+
+fetch_options() {
+    local params;
+    local exitStatus;
+
+    params=$(getopt --options c: --longoptions category: --name "$0" -- "$@")
+
+    exitStatus=$?
+    if [ $exitStatus -eq 0 ]; then
+        eval set -- "$params"
+
+        while true
+        do
+            case "$1" in
+                -c|--category)
+                    CATEGORY=$2
+                    shift 2
+                    ;;
+                --)
+                    shift
+                    ;;
+                "")
+                    break
+                    ;;
+                *)
+                    echo "Invalid argument: '$1'" >&2
+                    exitStatus=1
+                    shift
+                    ;;
+            esac
+        done
+    fi
+
+    if [ $exitStatus -ne 0 ]; then
+        echo "Call \"fetch-manuals --help\" to display help and valid options."
+        exit $exitStatus
+    fi
+}
 
 clone_manual() {
-    local repositoryUrl=$1
-    local branch=$2
-    local manualFolder=$3
+    local category=$1
+    local repositoryUrl=$2
+    local branch=$3
+    local manualFolder=$4
+
+    if [ "$CATEGORY" != "" ] && [ "$CATEGORY" != "$category" ]; then
+        echo "Skip cloning manual '$manualFolder'."
+        return 1
+    fi
 
     if [[ -d "$TARGET_BASEPATH/$manualFolder" ]]; then
         echo "Manual '$manualFolder' already exists."
@@ -28,18 +74,20 @@ clone_manual() {
 [[ ! -d "$TARGET_BASEPATH" ]] && mkdir "$TARGET_BASEPATH"
 cd "$TARGET_BASEPATH"
 
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid" "master" "TYPO3CMS-Book-ExtbaseFluid"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow" "master" "TYPO3CMS-Guide-ContributionWorkflow"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization" "master" "TYPO3CMS-Guide-FrontendLocalization"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument" "master" "TYPO3CMS-Guide-HowToDocument"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-Installation" "master" "TYPO3CMS-Guide-Installation"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-CoreApi" "master" "TYPO3CMS-Reference-CoreApi"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TCA" "master" "TYPO3CMS-Reference-TCA"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TSconfig" "master" "TYPO3CMS-Reference-TSconfig"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-Typoscript" "master" "TYPO3CMS-Reference-Typoscript"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-Editors" "master" "TYPO3CMS-Tutorial-Editors"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted" "master" "TYPO3CMS-Tutorial-GettingStarted"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage" "master" "TYPO3CMS-Tutorial-SitePackage"
-clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes" "master" "TYPO3CMS-Tutorial-Typoscript45Minutes"
+fetch_options $@
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid" "master" "TYPO3CMS-Book-ExtbaseFluid"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow" "master" "TYPO3CMS-Guide-ContributionWorkflow"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization" "master" "TYPO3CMS-Guide-FrontendLocalization"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument" "master" "TYPO3CMS-Guide-HowToDocument"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-Installation" "master" "TYPO3CMS-Guide-Installation"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-CoreApi" "master" "TYPO3CMS-Reference-CoreApi"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TCA" "master" "TYPO3CMS-Reference-TCA"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TSconfig" "master" "TYPO3CMS-Reference-TSconfig"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-Typoscript" "master" "TYPO3CMS-Reference-Typoscript"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-Editors" "master" "TYPO3CMS-Tutorial-Editors"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted" "master" "TYPO3CMS-Tutorial-GettingStarted"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage" "master" "TYPO3CMS-Tutorial-SitePackage"
+clone_manual "documentation" "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes" "master" "TYPO3CMS-Tutorial-Typoscript45Minutes"
+clone_manual "application" "git@github.com:FriendsOfTYPO3/extension_builder" "master" "extension_builder"
 
 cd - > /dev/null
