[TASK] Handle command line options in DDEV commands

diff --git a/.ddev/commands/web/init-screenshot-json b/.ddev/commands/web/init-screenshot-json
--- a/.ddev/commands/web/init-screenshot-json
+++ b/.ddev/commands/web/init-screenshot-json
@@ -1,12 +1,53 @@
 #!/bin/bash
 
 ## Description: Init basic screenshots.json inside the web container
-## Usage: init-screenshot-json (folder|path)
-## Example: "init-screenshot-json My-Manual" or "init-screenshot-json /var/www/html/t3docs/My-Manual"
+## Usage: init-screenshot-json
+## Example: init-screenshot-json -t My-Manual\ninit-screenshot-json -t /var/www/html/t3docs/My-Manual
+## Flags: [{"Name":"target-folder","Shorthand":"t","Usage":"Target folder by relative or absolute path. \"My-Manual\" if empty."}]
 
-init_screenshot_json() {
-    local manualFolder=${1}
-    typo3 screenshots:init $manualFolder
+TARGET_FOLDER=""
+
+fetch_options() {
+    local params;
+    local exitStatus;
+
+    params=$(getopt --options t: --longoptions target-folder: --name "$0" -- "$@")
+
+    exitStatus=$?
+    if [ $exitStatus -eq 0 ]; then
+        eval set -- "$params"
+
+        while true
+        do
+            case "$1" in
+                -t|--target-folder)
+                    TARGET_FOLDER=$2
+                    shift 2
+                    ;;
+                --)
+                    shift
+                    ;;
+                "")
+                    break
+                    ;;
+                *)
+                    echo "Invalid argument: '$1'" >&2
+                    exitStatus=1
+                    shift
+                    ;;
+            esac
+        done
+    fi
+
+    if [ $exitStatus -ne 0 ]; then
+        echo "Call \"init-screenshots-json --help\" to display help and valid options."
+        exit $exitStatus
+    fi
 }
 
-init_screenshot_json $@
+init_screenshot_json() {
+    typo3 screenshots:init $TARGET_FOLDER
+}
+
+fetch_options $@
+init_screenshot_json
diff --git a/.ddev/commands/web/run-unit-tests b/.ddev/commands/web/run-unit-tests
--- a/.ddev/commands/web/run-unit-tests
+++ b/.ddev/commands/web/run-unit-tests
@@ -2,11 +2,57 @@
 
 ## Description: Run unit tests of EXT:screenshots
 ## Usage: run-unit-tests
-## Example: "run-unit-tests"
+## Example: run-unit-tests\nrun-unit-tests -p "-d memory_limit=768M"\nrun-unit-tests -u "-v /var/www/html/packages/screenshots/Tests/Unit"
+## Flags: [{"Name":"php-flags","Shorthand":"p","Usage":"PHP command flags. None if empty."},{"Name":"phpunit-flags","Shorthand":"u","Usage":"PHPUnit command flags. \"/var/www/html/packages/screenshots/Tests/Unit\" if empty."}]
 
-run_unit_tests() {
-    local flags=${1:-"/var/www/html/packages/screenshots/Tests/Unit"}
-    phpunit $flags
+PHP_FLAGS=""
+PHPUNIT_FLAGS="/var/www/html/packages/screenshots/Tests/Unit"
+
+fetch_options() {
+    local params;
+    local exitStatus;
+
+    params=$(getopt --options p:u: --longoptions php-flags:phpunit-flags: --name "$0" -- "$@")
+
+    exitStatus=$?
+    if [ $exitStatus -eq 0 ]; then
+        eval set -- "$params"
+
+        while true
+        do
+            case "$1" in
+                -p|--php-flags)
+                    PHP_FLAGS=$2
+                    shift 2
+                    ;;
+                -u|--phpunit-flags)
+                    PHPUNIT_FLAGS=$2
+                    shift 2
+                    ;;
+                --)
+                    shift
+                    ;;
+                "")
+                    break
+                    ;;
+                *)
+                    echo "Invalid argument: '$1'" >&2
+                    exitStatus=1
+                    shift
+                    ;;
+            esac
+        done
+    fi
+
+    if [ $exitStatus -ne 0 ]; then
+        echo "Call \"run-unit-tests --help\" to display help and valid options."
+        exit $exitStatus
+    fi
 }
 
-run_unit_tests $@
+run_unit_tests() {
+    php $PHP_FLAGS /var/www/html/vendor/bin/phpunit $PHPUNIT_FLAGS
+}
+
+fetch_options $@
+run_unit_tests
